import ExcelJS from 'exceljs';
import { createPdfDocument, drawPdfText, finishPdf, pdfTextHeight } from '@/lib/pdf';

export type ReportColumn = { key: string; label: string; kind?: 'text' | 'money' | 'num' | 'date' };

export type ReportExportPayload = {
  type: string;
  title: string;
  periodLabel: string;
  columns: ReportColumn[];
  rows: Array<Record<string, unknown>>;
  summaries: Array<{ label: string; value: string | number }>;
  totalAmount: number;
};

const moneyFmt = new Intl.NumberFormat('en-GB', {
  style: 'currency',
  currency: 'GBP',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

function isCountLabel(label: string) {
  return /record|order|number|staff|product|document|supplier|employee|clock|late|absent|on time|page/i.test(label)
    && !/sales|paid|due|amount|value|expense|profit|purchase|income|stock value|average/i.test(label);
}

export function formatMoney(value: unknown) {
  return moneyFmt.format(Number(value || 0));
}

export function formatCell(value: unknown, kind?: ReportColumn['kind']) {
  if (value == null || value === '') return '-';
  if (kind === 'money') return formatMoney(value);
  if (kind === 'num' && typeof value === 'number') return String(value);
  return String(value);
}

function formatSummaryValue(item: { label: string; value: string | number }) {
  if (typeof item.value !== 'number') return String(item.value);
  if (isCountLabel(item.label)) return String(item.value);
  return formatMoney(item.value);
}

function columnWeight(col: ReportColumn) {
  const key = `${col.key} ${col.label}`.toLowerCase();
  if (col.kind === 'money') return 1.1;
  if (col.kind === 'num') return 0.7;
  if (/invoice|product|employee|customer|supplier|description|title|person|account|lender/.test(key)) return 1.6;
  if (/status|method|qty|items|hours|stock|direction/.test(key)) return 0.8;
  if (col.kind === 'date') return 1.35;
  return 1;
}

function layoutColumns(columns: ReportColumn[], tableWidth: number) {
  const weights = columns.map(columnWeight);
  const total = weights.reduce((s, w) => s + w, 0) || 1;
  return columns.map((col, i) => ({
    ...col,
    width: Math.max(42, (tableWidth * weights[i]) / total)
  }));
}

function appliedFiltersText(filters?: Record<string, string | null | undefined>, q?: string | null) {
  const parts: string[] = [];
  if (q) parts.push(`Search: ${q}`);
  Object.entries(filters || {}).forEach(([key, value]) => {
    if (!value) return;
    parts.push(`${key.replace(/([A-Z])/g, ' $1')}: ${value}`);
  });
  return parts.length ? parts.join('  ·  ') : 'None (all matching records)';
}

export async function buildStructuredExcel(input: {
  data: ReportExportPayload;
  generatedBy?: string;
  filters?: Record<string, string | null | undefined>;
  q?: string | null;
  filename: string;
}) {
  const { data } = input;
  const generatedAt = new Date();
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'THE OUDS Management';
  const summary = workbook.addWorksheet('Summary');
  const details = workbook.addWorksheet('Details');

  summary.addRow(['THE OUDS Management']);
  summary.addRow([data.title]);
  summary.addRow(['Date range', data.periodLabel]);
  summary.addRow(['Generated', generatedAt.toLocaleString('en-GB')]);
  summary.addRow(['Generated by', input.generatedBy || '']);
  summary.addRow(['Applied filters', appliedFiltersText(input.filters, input.q)]);
  summary.addRow([]);
  summary.addRow(['Metric', 'Value']);
  data.summaries.forEach((s) => summary.addRow([s.label, typeof s.value === 'number' && !isCountLabel(s.label) ? Number(s.value) : s.value]));
  summary.addRow(['Total records', data.rows.length]);
  if (data.totalAmount) summary.addRow(['Total amount', data.totalAmount]);
  summary.getColumn(1).width = 28;
  summary.getColumn(2).width = 22;
  summary.getRow(8).font = { bold: true };

  details.addRow(data.columns.map((c) => c.label));
  details.getRow(1).font = { bold: true };
  details.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF2F4F7' } };
  data.rows.forEach((row) => {
    details.addRow(data.columns.map((c) => (c.kind === 'money' ? Number(row[c.key] || 0) : row[c.key] ?? '')));
  });
  data.columns.forEach((col, i) => {
    const column = details.getColumn(i + 1);
    column.width = col.kind === 'money' || col.kind === 'num' ? 14 : col.kind === 'date' ? 20 : 22;
    if (col.kind === 'money') column.numFmt = '"£"#,##0.00';
  });
  const lastCol = String.fromCharCode(64 + Math.min(26, data.columns.length));
  details.views = [{ state: 'frozen', ySplit: 1 }];
  details.autoFilter = { from: 'A1', to: `${lastCol}1` };
  if (data.columns.some((c) => c.kind === 'money')) {
    const totals = data.columns.map((c) => (c.kind === 'money' ? data.rows.reduce((s, r) => s + Number(r[c.key] || 0), 0) : ''));
    const totalRow = details.addRow(totals);
    totalRow.font = { bold: true };
  }

  return {
    buffer: await workbook.xlsx.writeBuffer(),
    filename: input.filename,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  };
}

export async function buildStructuredPdf(input: {
  data: ReportExportPayload;
  generatedBy?: string;
  filters?: Record<string, string | null | undefined>;
  q?: string | null;
  filename: string;
}) {
  const { data } = input;
  const generatedAt = new Date();
  const generatedLabel = generatedAt.toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  const landscape = data.columns.length >= 6;
  const doc = createPdfDocument({
    margin: 36,
    size: 'A4',
    layout: landscape ? 'landscape' : 'portrait',
    bufferPages: true
  });

  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const left = 36;
  const right = pageWidth - 36;
  const tableWidth = right - left;
  const cols = layoutColumns(data.columns, tableWidth);
  const footerY = pageHeight - 28;
  const tableBottom = pageHeight - 48;

  const drawHeaderBand = () => {
    doc.fontSize(16).fillColor('#111');
    drawPdfText(doc, 'THE OUDS Management', left, 32, { width: tableWidth, bold: true });
    doc.fontSize(13);
    drawPdfText(doc, data.title, left, 52, { width: tableWidth, bold: true });
    doc.fontSize(9).fillColor('#444');
    drawPdfText(doc, `Date range: ${data.periodLabel}`, left, 72, { width: tableWidth / 2 });
    drawPdfText(doc, `Generated: ${generatedLabel}`, left + tableWidth / 2, 72, { width: tableWidth / 2, align: 'right' });
    drawPdfText(doc, `Generated by: ${input.generatedBy || 'Admin'}`, left, 86, { width: tableWidth / 2 });
    drawPdfText(doc, `Records: ${data.rows.length}`, left + tableWidth / 2, 86, { width: tableWidth / 2, align: 'right' });
    doc.fillColor('#111');
  };

  const drawSummary = (startY: number) => {
    const cards = data.summaries.slice(0, 6);
    if (!cards.length) return startY;
    const gap = 8;
    const cardW = (tableWidth - gap * (cards.length - 1)) / cards.length;
    const cardH = 42;
    cards.forEach((item, i) => {
      const x = left + i * (cardW + gap);
      doc.roundedRect(x, startY, cardW, cardH, 4).strokeColor('#d0d5dd').lineWidth(0.8).stroke();
      doc.fontSize(8).fillColor('#667085');
      drawPdfText(doc, item.label, x + 8, startY + 7, { width: cardW - 16 });
      doc.fontSize(11).fillColor('#111');
      drawPdfText(doc, formatSummaryValue(item), x + 8, startY + 20, { width: cardW - 16, bold: true });
    });
    return startY + cardH + 12;
  };

  const drawTableHeader = (y: number) => {
    let x = left;
    const h = 22;
    doc.rect(left, y, tableWidth, h).fill('#f2f4f7');
    doc.fillColor('#344054').fontSize(8);
    cols.forEach((col) => {
      const align = col.kind === 'money' || col.kind === 'num' ? 'right' : 'left';
      drawPdfText(doc, col.label, x + 4, y + 7, { width: col.width - 8, align, bold: true });
      x += col.width;
    });
    doc.strokeColor('#d0d5dd').lineWidth(0.6).moveTo(left, y + h).lineTo(right, y + h).stroke();
    return y + h;
  };

  const rowHeightFor = (row: Record<string, unknown>) => {
    let h = 18;
    cols.forEach((col) => {
      const text = formatCell(row[col.key], col.kind);
      const needed = pdfTextHeight(doc, text, { width: col.width - 8, lineGap: 1 }) + 8;
      h = Math.max(h, Math.min(48, needed));
    });
    return h;
  };

  const drawRow = (row: Record<string, unknown>, y: number, index: number) => {
    const h = rowHeightFor(row);
    if (index % 2 === 1) {
      doc.rect(left, y, tableWidth, h).fill('#fafafa');
    }
    let x = left;
    cols.forEach((col) => {
      const align = col.kind === 'money' || col.kind === 'num' ? 'right' : 'left';
      doc.fillColor('#111').fontSize(8);
      drawPdfText(doc, formatCell(row[col.key], col.kind), x + 4, y + 4, {
        width: col.width - 8,
        align,
        lineGap: 1,
        height: h - 6
      });
      x += col.width;
    });
    doc.strokeColor('#eaecf0').lineWidth(0.4).moveTo(left, y + h).lineTo(right, y + h).stroke();
    return y + h;
  };

  drawHeaderBand();
  doc.fontSize(9).fillColor('#444');
  drawPdfText(doc, `Applied filters: ${appliedFiltersText(input.filters, input.q)}`, left, 102, {
    width: tableWidth
  });
  let y = drawSummary(118);
  y = drawTableHeader(y);

  if (!data.rows.length) {
    doc.fontSize(10).fillColor('#667085');
    drawPdfText(doc, 'No rows for this filter.', left, y + 12);
  } else {
    data.rows.forEach((row, index) => {
      const h = rowHeightFor(row);
      if (y + h > tableBottom) {
        doc.addPage();
        drawHeaderBand();
        y = drawTableHeader(108);
      }
      y = drawRow(row, y, index);
    });
  }

  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    doc.fontSize(8).fillColor('#667085');
    drawPdfText(doc, 'THE OUDS Management', left, footerY, { width: tableWidth / 3 });
    drawPdfText(doc, `Generated by ${input.generatedBy || 'Admin'} · ${generatedLabel}`, left + tableWidth / 3, footerY, {
      width: tableWidth / 3,
      align: 'center'
    });
    drawPdfText(doc, `Page ${i + 1} of ${range.count}`, left + (tableWidth * 2) / 3, footerY, {
      width: tableWidth / 3,
      align: 'right'
    });
  }

  return {
    buffer: await finishPdf(doc),
    filename: input.filename,
    contentType: 'application/pdf'
  };
}
